### ISSUE TITLE
Remove Scenario from DB

### ISSUE THREAD

**Issue by tzipperle** [iiasa/ixmp#153]
Hi,
Is it possible to delete a Scenario from the database? Because the HyperSQL database becomes very large after a sensitivity analysis with 1000 runs.

**Comment by danielhuppmann** [comment]
Thanks for this suggestion. We don't have an explicit feature for this yet (because in a shared database, you need some sort of "ownership" or rights management to prevent inadvertently deleting another users scenario.

In the meantime, the new release supports cloning across platforms, so you can now easily copy a scenario to a new db instance and run all related sensitivity analysis there. This has the additional benefit of separating the main scenarios and the sensitivity analysis.

**Comment by tzipperle** [comment]
That make sense with the database management. I will use the new clone function to keep a clear overview of my databases.

**Comment by khaeru** [comment]
@danielhuppmann just 'assigned' simply to give you credit for answering this question last year :+1: nothing further to be done!
