### ISSUE TITLE
How to have VTG and YEAR into new parameter with init_par

### ISSUE THREAD

**Issue by DIUANA** [iiasa/ixmp#272]
HI all
Once again I am in doubt if this issue should be raised here or in message_ix so feel free to adjust it,

My doubt regards the init_par function but it can be extended to other init functions since they have the same issue,

I am trying to add a new parameter to to message e,g,
`scenario.init_par('A',['node','technology','vintage','year','time'] )`

however vintage is not recognized and I got the error message:
 **There exists no index set 'vintage'!**

If I try 
`scenario.init_par('A',['node','technology','year','year','time'] )`

I got a new error message:
 **The index names are not unique!**

How can I overcome this? Is there a way out?

Thanks in advance

**Comment by khaeru** [comment]
Per [the documentation for `init_par`](https://message.iiasa.ac.at/projects/ixmp/en/stable/api-python.html#ixmp.Scenario.init_par), there are **two** parameters you can use:
- *idx_sets* is the "names of [**existing**] sets that index this parameter". Your first example probably does not work because 'vintage' is not a set in the Scenario you are using. Correct?
- *idx_names* is the "names of the dimensions indexed by *idx_sets*".

In your second example, where two dimensions are indexed by the *same* set, it would be ambiguous to add data to the resulting parameter 'A' using `add_par()`—the input data frame would need two columns both named 'year', and it would be unclear which was which. In this case, ixmp requires you to also give the *idx_names* parameter.

If this answers your question, please close the issue.
If you can suggest a way to rephrase the documentation to help others understand this more easily, please open a PR with your changes!

**Comment by DIUANA** [comment]
Once again many thanks Paul This completely answer my question. It was not clear for me the role of the idx_names. 

However now that I have read your explanation the documentation looks good to me. I believe this misunderstanding is more on me than on documentation.
