### ISSUE TITLE
installation problem llvmlite error

### ISSUE THREAD

**Issue by DIUANA** [iiasa/ixmp#337]
#### Code sample or context
Hi, I hope you are doing fine during quarantine.

I am having a hard time to install ixmp from source 
Actually every time I have to do it I face an issue however this one is more complex because everything I try I get the same message error.I have tried with the latest Anaconda version and also with an older version and both them show me a message related to llvmlite.

![image](https://user-images.githubusercontent.com/37837898/84971522-58b4b200-b0f3-11ea-9ff1-8402e496209b.png)

The three first erros change according to my different attempts but the last one, the one that breaks the installation is always the same.

How can deal with it? All the best

#### Versions

<details><summary>Output of <tt>ixmp show-versions</tt></summary>

```
<!--
  Run one of the following and paste the results here:
  - 'ixmp show-versions' in a terminal, or
  - 'import ixmp; ixmp.show_versions()' in a Python interpreter.
-->
```

</details>

**Comment by khaeru** [comment]
In iiasa/message_ix#364, it seems that your issues were related to using Anaconda without creating a new environment in which to install message_ix. That situation could also cause this issue: Anaconda, in its default/base environment, will refuse to remove or change packages that are 'pinned' to certain versions, such as `llvmlite`.

I can't tell if that's what you're doing, because the information is provided as a screenshot. After you've followed the suggestion at https://github.com/iiasa/message_ix/issues/364#issuecomment-645894975, please either:
- Close this issue if it is no longer relevant,
- Report if the install from source instructions again work, then close the issue, or
- Provide complete information including which terminal (Windows Command Prompt or Anaconda Prompt) and which specific command produced this output. 

Please always include complete error messages, as text (in triple backticks \`\`\`) rather than as a screenshot.

**Comment by DIUANA** [comment]
Sorry Paul, I will try to provide you all information in the next time.

- When I tried to install from source I did not create a new environment since I had never done it before. Apparently it is a new recommendation.

- I am using Anaconda prompt 
- I tried with 3 different anaconda versions, including the latest one.
- The command that produced this output was `pip install --editable .[docs,tests,tutorial]` in the folder I cloned the repo.

Now I tried to install from source in a new environment it worked just fine. 

Thanks Paul
