### ISSUE TITLE
Issue when adding bound_emission parameter

### ISSUE THREAD

**Issue by Jaspergeipel** [iiasa/ixmp#37]
Dear all, 
I tried to add a cap on the GHGs emissions by adding the the bound_emission parameter: 
bound_emission = pd.DataFrame({
        'node': country,
        'type_emission': 'GHGs',
        'type_tec': 'all',
        'type_year': horizon[1:],
        'value': emission_cap_year,
        'unit': 'kg/kWa',
})
scenario.add_par('bound_emission', bound_emission)
However I get the following error message: 

"at.ac.iiasa.ixmp.exceptions.IxExceptionPyRaisable: at.ac.iiasa.ixmp.exceptions.IxException: The index set 'type_year' does not have an element '2020'!"

Best
jasper

**Comment by danielhuppmann** [comment]
hi @Jaspergeipel , you need to define first that the year `2020` is not only a year, but also part of a "category". You can do this by using the command

``scenario.add_cat('year', y, y)``

where `y` is the year.

This will create an element `y` in the set `type_year` and map the year `y` to this type. Note that in the current version, you have to turn `y` into a string, but this will be fixed in the next `ixmp` update.

This may look overly complicated, but it is actually helpful when you want to define constraints (as averages) over sets of years, technologies or nodes.

For example, you can set a bound on emissions over the entire time horizon by defining a `type year 'cumulative'` using

``scenario.add_cat('year', 'cumulative', years)``,

where years is the list of years.
