### ISSUE TITLE
JDBCBackend.__del__ raises ignored exception when JVM has shut down

### ISSUE THREAD

**Issue by zsalimian** [iiasa/ixmp#377]
I installed message-ix and then I verified the installation by the following command:
$message-ix show-versions
![Untitled3](https://user-images.githubusercontent.com/71164512/97288103-a0dea080-185a-11eb-916c-51a0df0ba35b.png)

but after using the following command,the system showed me the following error:
$message-ix --platform=default list

![Untitled](https://user-images.githubusercontent.com/71164512/97287696-21e96800-185a-11eb-9957-77a7f6942da4.png)

**Comment by zsalimian** [comment]
Dear @khaeru 
Thank you for your comment.
Should I use JDBCBackend to solve the problem?how?
Regards

**Comment by khaeru** [comment]
>  Should I use JDBCBackend to solve the problem?how?

To repeat what I said, in different words: there is no problem. The software is working fine. The "error" message doesn't affect anything.

However, I agree the message is a little annoying or confusing. I am opened the linked pull request, #378, which will hide the message. But, again, since this does not affect the operation of the software, you can continue to use it. Just ignore the message.

Please let me know if that is not sufficiently clear.
