### ISSUE TITLE
ImportError: DLL load failed while importing _jpype

### ISSUE THREAD

**Issue by vahabmokari** [iiasa/ixmp#380]
Hi,
Please see the following error that happened when I run the following command
$message-ix show versions
Would you please guide me how to solve this problem?
Regards
![Untitled](https://user-images.githubusercontent.com/73784155/97804531-da057f00-1c65-11eb-9fa8-86a5a735e2c8.png)

**Comment by vahabmokari** [comment]
Dear Sir,
Yes. I have installed message-ix via Miniconda successfully. And I run the samples in tutorial.
Now, I would like to try installing from source as it makes me possible to work with python as well as work with message-ix professionally.
You are right! I tried to install it from source. And the above error in the screenshot occurred when I run $message-ix show-versions.
As you said I tried  to reinstall JPype1, which you mentioned above.
I run the $ pip install JPype1
It showed me the following message:
**Requirement already satisfied : JPype1 in  Python\lib\site-packages (1.1.2)**
Again I run $message-ix show-versions.
It still shows the above error in the above screen shot
Would you please guide me how to solve the problem?
Regards

**Comment by khaeru** [comment]
> As you said I tried to reinstall JPype1, which you mentioned above.
> I run the `$ pip install JPype1`
> It showed me the following message:
> `Requirement already satisfied : JPype1 in Python\lib\site-packages (1.1.2)`

Whether you install message_ix from source, PyPI, or conda, is **separate** from whether you install JPype1 from source, PyPI, or conda. My last comment was about the latter, not the former. If you are using Anaconda/Miniconda, you should use `conda install`, not `pip install`, for **all dependencies** except message_ix itself. This is true *regardless* of how message_ix itself is installed (source, PyPI, or conda).

Please be sure to read the [documentation page on prerequisite knowledge](https://docs.messageix.org/en/stable/prereqs.html) and use the links to fill any gaps. Understanding these distinctions is part of that prerequisite knowledge.

The initial mistake—using `pip install` instead of `conda install` for JPype—is the cause of the later error message. `conda install` will install the correct DLL files that are compatible with the other packages in your conda environment. `pip install` in some conditions (like yours) will not do this.
