### ISSUE TITLE
Default logLevel DEBUG or INFO?

### ISSUE THREAD

**Issue by tzipperle** [iiasa/ixmp#55]
Inside the PyCharm Console, I always get messages at the DEBUG level:

![image](https://user-images.githubusercontent.com/6015123/41891891-7ac283de-7916-11e8-9828-a4540c0e7b23.png)

However, when I look to `ixmp/ixmp/utils.py` is this for me not clear, because the level is only set there to INFO:

```
def logger():
    """Access global logger"""
    global _LOGGER
    if _LOGGER is None:
        logging.basicConfig()
        _LOGGER = logging.getLogger()
        _LOGGER.setLevel('INFO')
    return _LOGGER
```
Is there another possibility to change the logging level?

**Comment by danielhuppmann** [comment]
Sorry, I believe that the output in your screenshot is determined in the compiled `ixmp.jar`, and this is distinct from the `_LOGGER.setLevel()`. Not sure why this was changed in the first place before the latest release.

We will rework the Java logging in the next release.

**Comment by tzipperle** [comment]
Make sense, because I could not get access via the python logging root handler...

**Comment by gidden** [comment]
@zikolach and @fonfon would it be possible to access and set the log level in java from python as well?

**Comment by zikolach** [comment]
@gidden you can do it by programmatically by calling e.g.:

```
org.apache.log4j.Logger.getLogger(Platform.class.getPackage().getName()).setLevel(org.apache.log4j.Level.DEBUG)
```

Alternatively I can add a (static) method to Platform class for setting it. But we have bundled log4j.properties file with some predefined settings:

```
log4j.appender.FA=org.apache.log4j.DailyRollingFileAppender
log4j.appender.FA.file=D:/tmp/GasmAgeServlet-app.log
log4j.rootLogger=FA, stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %5p %c:%L - %m%n
log4j.logger.at.ac.iiasa.kolp.cleanage.servlet.DatabaseHelper=info
log4j.logger.at.ac.iiasa.ixmp.servlet.AuthDbFilter=info
log4j.logger.at.ac.iiasa.ixmp.servlet.RestServlet=debug
```

which I would replace with

```
log4j.rootLogger=WARN, stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %5p %c:%L - %m%n
log4j.logger.org.flywaydb.core.internal=warn
```

as default

**Comment by khaeru** [comment]
Hi @tzipperle —going to close this now since the code is substantially changed and I don't suspect this can occur anymore. Now, the top-level ("ixmp") logger is configured here:
https://github.com/iiasa/ixmp/blob/59e99e47082a52203e493a5b0b68afc65506e469/ixmp/__init__.py#L44-L48

The Java backend, at the point when any new Platform is instantiated, uses either a user argument or copies this value:
https://github.com/iiasa/ixmp/blob/59e99e47082a52203e493a5b0b68afc65506e469/ixmp/backend/jdbc.py#L212-L216

After this, the `mp.set_log_level()` method can be used to control the log messages emitted from Java. At any time or point, the "ixmp" logger can be manipulated in the usual Python way.

If any similar issue is still happening with the newest code, please open a new issue.
